### PR TITLE
Untrack dist folder

### PR DESCRIPTION
**Pull request by TheCre8tor**

### CODE REVIEW

**Comment by TheCre8tor** [comment]
Hi @gomain, I tried requesting a reviewer but your profile is not showing up.

Screenshot 2023-02-02 at 11 49 32 AM

**Review by gomain — APPROVED** [review]
Greate.

**Comment by gomain** [comment]
Let's merge this change. Then rebase the other PR on **main**.

**Comment by gomain** [comment]
> Hi @gomain, I tried requesting a reviewer but your profile is not showing up.

I think you'll have to add me to the repo first. (not sure what that even means).

**Pull request merged**
